### ISSUE TITLE
usage of relative path

### ISSUE THREAD

**Issue by mrijken** [faassen/bowerstatic#26]
Line https://github.com/faassen/bowerstatic/blob/master/bowerstatic/core.py#L239 will make that components will only work with absolute paths. Relative paths will not work. Is that by design?

**Comment by ismail-s** [comment]
@faassen I have a concrete example of this inability of components to reference other components causing issues. Namely, polymer. See https://github.com/Polymer/polymer/blob/0.5.x/index.html#L13 for an example of an offending line.
