### ISSUE TITLE
Some typos in integrating.rst

### ISSUE THREAD

**Issue by henri-hulski** [faassen/bowerstatic#50]
I found some typos in the examples for [Supporting additional types of resources](https://github.com/faassen/bowerstatic/blob/master/doc/integrating.rst#supporting-additional-types-of-resources) and [Custom renderer](https://github.com/faassen/bowerstatic/blob/master/doc/integrating.rst#custom-renderer).
For registering a renderer it should be bower.register_renderer not bower.renderer and after resource.url are missing parentheses:
``` python
def render_foo(resource):
     return "<foo>%s</foo>" % resource.url()
```
``` python
bower.register_renderer('.foo', render_foo)
```
``` python
bower.register_renderer('.foo', "<foo>{url}</foo>")
```
``` python
include('static/favicon.ico', lambda resource: '<link rel="shortcut icon" type="image/x-icon" href="' + resource.url() + '"/>')
```

By the way, I've written a **JSX renderer for bowerstatic** based on [PyReact](https://github.com/reactjs/react-python):
``` python
import bowerstatic
from react import jsx

bower = bowerstatic.Bower()


def render_jsx(resource):
    jsx_path = bowerstatic.module_relative_path('static') + '/' + resource.file_path
    js_path = jsx_path[:-1]
    transformer = jsx.JSXTransformer()
    transformer.transform(jsx_path, js_path)
    js_url = resource.url()[:-1]
    return '<script type="text/javascript" src="%s"></script>' % js_url

bower.register_renderer('.jsx', render_jsx)
```
It transforms the JSX file to a plain javascipt file, save it in the same directory and include it in a script tag.

If you are interested you can include it, but it has PyReact, PyExecJS and a Python JS engine as dependencies so maybe better create a React extension or just include it as an example in the docs.

Regards,
Henri

**Comment by henri-hulski** [comment]
I have make a PR to fix the typos.
If you're interested I can also make a PR to include the JSX renderer as an examle in the docs.
Just tell me, where is the best place for it.

**Comment by faassen** [comment]
Hey, I don't see this show up as a PR in bowerstatic proper. I can see the changes but it isn't a pull request for the project?

Concerning a JSX transformer: there are so many ways to make sure that JSX is executed, including the specific jsx script, including the JSX JS, using babel + webpack, etc, that I think it may lead to conclusion if we promote this as the bowerstatic way to do things.

I think a better approach would be to create an extension to bowerstatic that helps you do it and document it there. We can then point to this from the docs.

**Comment by henri-hulski** [comment]
Ok.  It seems that I have made a PR in my own repo. 
Now it's fixed. 

Actually I also switched to webpack. But this one was nice for debugging having the plain javascript always in place. 
Maybe it could go in the recipes section of morepath which you are planning.

**Comment by henri-hulski** [comment]
Or what about recipes for bowerstatic?

**Comment by faassen** [comment]
If I can choose between code I can install versus a recipe that I have to copy myself, I prefer installable code. A recipe would be fine if its primary goal is education about how to write a renderer in the first place.

**Comment by henri-hulski** [comment]
Maybe the educational value is the most important here. 
You can adapt the code also to integrate other javascript dialects like Coffee script etc.

**Comment by faassen** [comment]
I'm happy to include documentation that describes how to use renderers to do clever stuff like transformation. I'm slightly concerned about renderer actually writing files to the filesystem. It'd be nicer if BowerStatic could do a transformation in memory and create a reference to the transformation, but this would require much more sophistication. It kind of steps out of what bower and thus BowerStatic are trying to do -- such sophisticated use cases should really use JavaScript native tools that know more about packaging, such as webpack or browserify.

**Comment by henri-hulski** [comment]
As I said I've  also switched from Bowerstatic to webpack using the [script](https://www.google.com/url?q=https%3A%2F%2Fgist.github.com%2Fhref%2Fa4edb486bfac45521342&sa=D&sntz=1&usg=AFQjCNFmqscExMdQED8cGaXxIdBWyyfwbA)  from Denis for serving the static directory. 
By the way, I really would like to see this functionality native in Morepath. 

Regarding the JSX transformer, I liked to have the javascript file beside the JSX file to understand how it gets transformed. I think for a newbie that can be helpful. 
But I'm agree that in a production setup you rather will use Javascript native tools. 
So I think I close that issue for now.
